/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AggregateSearch: typeof import('./components/molecules/AggregateSearch.vue')['default']
    AvatarUpload: typeof import('./components/organisms/AvatarUpload.vue')['default']
    BaseBadge: typeof import('./components/atoms/BaseBadge.vue')['default']
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseChatBubble: typeof import('./components/atoms/BaseChatBubble.vue')['default']
    BaseCheckbox: typeof import('./components/atoms/BaseCheckbox.vue')['default']
    BaseCitationChip: typeof import('./components/atoms/BaseCitationChip.vue')['default']
    BaseInput: typeof import('./components/atoms/BaseInput.vue')['default']
    BaseMessageGroup: typeof import('./components/molecules/BaseMessageGroup.vue')['default']
    BaseToolTag: typeof import('./components/atoms/BaseToolTag.vue')['default']
    ChartEmpty: typeof import('./components/molecules/ChartEmpty.vue')['default']
    ChatPanel: typeof import('./components/organisms/ChatPanel.vue')['default']
    CountdownCard: typeof import('./components/organisms/CountdownCard.vue')['default']
    DailyGreeting: typeof import('./components/organisms/DailyGreeting.vue')['default']
    DigitRoll: typeof import('./components/atoms/DigitRoll.vue')['default']
    EarningsClock: typeof import('./components/organisms/EarningsClock.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    KnowledgeSidebar: typeof import('./components/organisms/KnowledgeSidebar.vue')['default']
    LinkDock: typeof import('./components/organisms/LinkDock.vue')['default']
    MiniCalendar: typeof import('./components/organisms/MiniCalendar.vue')['default']
    MobileBottomNav: typeof import('./components/organisms/MobileBottomNav.vue')['default']
    MyDay: typeof import('./components/organisms/MyDay.vue')['default']
    PageHeader: typeof import('./components/organisms/PageHeader.vue')['default']
    PasswordStrengthMeter: typeof import('./components/atoms/PasswordStrengthMeter.vue')['default']
    ProductivityHeatmap: typeof import('./components/organisms/ProductivityHeatmap.vue')['default']
    ReminderBell: typeof import('./components/molecules/ReminderBell.vue')['default']
    RollingAmount: typeof import('./components/molecules/RollingAmount.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/molecules/SearchBar.vue')['default']
    SettingsPanel: typeof import('./components/organisms/SettingsPanel.vue')['default']
    SidebarNav: typeof import('./components/organisms/SidebarNav.vue')['default']
    StatisticsCard: typeof import('./components/organisms/StatisticsCard.vue')['default']
    StatsHourHeatmap: typeof import('./components/organisms/StatsHourHeatmap.vue')['default']
    StatsRangeTabs: typeof import('./components/molecules/StatsRangeTabs.vue')['default']
    StatsScatterChart: typeof import('./components/organisms/StatsScatterChart.vue')['default']
    StatsTagDonut: typeof import('./components/organisms/StatsTagDonut.vue')['default']
    StatsTrendChart: typeof import('./components/organisms/StatsTrendChart.vue')['default']
    StreakCard: typeof import('./components/organisms/StreakCard.vue')['default']
    ThemeToggle: typeof import('./components/molecules/ThemeToggle.vue')['default']
    TitleBar: typeof import('./components/organisms/TitleBar.vue')['default']
    TodayProgressCard: typeof import('./components/organisms/TodayProgressCard.vue')['default']
    TodoForm: typeof import('./components/organisms/TodoForm.vue')['default']
    TodoItem: typeof import('./components/molecules/TodoItem.vue')['default']
    TodoList: typeof import('./components/organisms/TodoList.vue')['default']
    TrendBadge: typeof import('./components/atoms/TrendBadge.vue')['default']
    TurnstileCaptcha: typeof import('./components/atoms/TurnstileCaptcha.vue')['default']
    UiIcon: typeof import('./components/atoms/UiIcon.vue')['default']
    WallpaperSettings: typeof import('./components/organisms/WallpaperSettings.vue')['default']
    WeatherWidget: typeof import('./components/organisms/WeatherWidget.vue')['default']
  }
}
